// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvgbbkdpbcvaezvteggd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2Z2Jia2RwYmN2YWV6dnRlZ2dkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExMjE5NjQsImV4cCI6MjA4NjY5Nzk2NH0.w9dUvoOebnmTdNTRwLWORzglewTdywlb1Q3itKS63yM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});